/**
 * Common emoji list for the emoji picker
 * Sourced from Github's gemoji project (MIT License)
 * https://github.com/github/gemoji/blob/master/db/emoji.json
 */

export interface Emoji {
  emoji: string
  description: string
  category: string
  aliases: string[]
  tags: string[]
}

const emojiList: Emoji[] = [
  // Smileys & Emotion
  { emoji: '😀', description: 'grinning face', category: 'Smileys & Emotion', aliases: ['grinning'], tags: ['smile', 'happy'] },
  { emoji: '😃', description: 'grinning face with big eyes', category: 'Smileys & Emotion', aliases: ['smiley'], tags: ['happy', 'joy', 'haha'] },
  { emoji: '😄', description: 'grinning face with smiling eyes', category: 'Smileys & Emotion', aliases: ['smile'], tags: ['happy', 'joy', 'laugh', 'pleased'] },
  { emoji: '😁', description: 'beaming face with smiling eyes', category: 'Smileys & Emotion', aliases: ['grin'], tags: [] },
  { emoji: '😆', description: 'grinning squinting face', category: 'Smileys & Emotion', aliases: ['laughing', 'satisfied'], tags: ['happy', 'haha'] },
  { emoji: '😅', description: 'grinning face with sweat', category: 'Smileys & Emotion', aliases: ['sweat_smile'], tags: ['hot'] },
  { emoji: '🤣', description: 'rolling on the floor laughing', category: 'Smileys & Emotion', aliases: ['rofl'], tags: ['lol', 'laughing'] },
  { emoji: '😂', description: 'face with tears of joy', category: 'Smileys & Emotion', aliases: ['joy'], tags: ['tears'] },
  { emoji: '🙂', description: 'slightly smiling face', category: 'Smileys & Emotion', aliases: ['slightly_smiling_face'], tags: [] },
  { emoji: '🙃', description: 'upside-down face', category: 'Smileys & Emotion', aliases: ['upside_down_face'], tags: [] },
  { emoji: '😉', description: 'winking face', category: 'Smileys & Emotion', aliases: ['wink'], tags: ['flirt'] },
  { emoji: '😊', description: 'smiling face with smiling eyes', category: 'Smileys & Emotion', aliases: ['blush'], tags: ['proud'] },
  { emoji: '😇', description: 'smiling face with halo', category: 'Smileys & Emotion', aliases: ['innocent'], tags: ['angel'] },
  { emoji: '🥰', description: 'smiling face with hearts', category: 'Smileys & Emotion', aliases: ['smiling_face_with_three_hearts'], tags: ['love'] },
  { emoji: '😍', description: 'smiling face with heart-eyes', category: 'Smileys & Emotion', aliases: ['heart_eyes'], tags: ['love', 'crush'] },
  { emoji: '🤩', description: 'star-struck', category: 'Smileys & Emotion', aliases: ['star_struck'], tags: ['wow'] },
  { emoji: '😘', description: 'face blowing a kiss', category: 'Smileys & Emotion', aliases: ['kissing_heart'], tags: ['flirt'] },
  { emoji: '😗', description: 'kissing face', category: 'Smileys & Emotion', aliases: ['kissing'], tags: [] },
  { emoji: '😚', description: 'kissing face with closed eyes', category: 'Smileys & Emotion', aliases: ['kissing_closed_eyes'], tags: [] },
  { emoji: '😙', description: 'kissing face with smiling eyes', category: 'Smileys & Emotion', aliases: ['kissing_smiling_eyes'], tags: [] },
  { emoji: '🥲', description: 'smiling face with tear', category: 'Smileys & Emotion', aliases: ['smiling_face_with_tear'], tags: [] },
  { emoji: '😋', description: 'face savoring food', category: 'Smileys & Emotion', aliases: ['yum'], tags: ['tongue', 'lick'] },
  { emoji: '😛', description: 'face with tongue', category: 'Smileys & Emotion', aliases: ['stuck_out_tongue'], tags: [] },
  { emoji: '😜', description: 'winking face with tongue', category: 'Smileys & Emotion', aliases: ['stuck_out_tongue_winking_eye'], tags: ['prank', 'silly'] },
  { emoji: '🤪', description: 'zany face', category: 'Smileys & Emotion', aliases: ['zany_face'], tags: ['goofy', 'wacky'] },
  { emoji: '😝', description: 'squinting face with tongue', category: 'Smileys & Emotion', aliases: ['stuck_out_tongue_closed_eyes'], tags: ['prank'] },
  { emoji: '🤑', description: 'money-mouth face', category: 'Smileys & Emotion', aliases: ['money_mouth_face'], tags: ['rich'] },
  { emoji: '🤗', description: 'smiling face with open hands', category: 'Smileys & Emotion', aliases: ['hugs'], tags: [] },
  { emoji: '🤭', description: 'face with hand over mouth', category: 'Smileys & Emotion', aliases: ['hand_over_mouth'], tags: ['quiet', 'whoops'] },
  { emoji: '🤫', description: 'shushing face', category: 'Smileys & Emotion', aliases: ['shushing_face'], tags: ['quiet', 'secret'] },
  { emoji: '🤔', description: 'thinking face', category: 'Smileys & Emotion', aliases: ['thinking'], tags: [] },
  { emoji: '🤐', description: 'zipper-mouth face', category: 'Smileys & Emotion', aliases: ['zipper_mouth_face'], tags: ['secret', 'quiet'] },
  { emoji: '🤨', description: 'face with raised eyebrow', category: 'Smileys & Emotion', aliases: ['raised_eyebrow'], tags: ['suspicious'] },
  { emoji: '😐', description: 'neutral face', category: 'Smileys & Emotion', aliases: ['neutral_face'], tags: ['meh'] },
  { emoji: '😑', description: 'expressionless face', category: 'Smileys & Emotion', aliases: ['expressionless'], tags: [] },
  { emoji: '😶', description: 'face without mouth', category: 'Smileys & Emotion', aliases: ['no_mouth'], tags: ['mute', 'silence'] },
  { emoji: '😏', description: 'smirking face', category: 'Smileys & Emotion', aliases: ['smirk'], tags: ['smug'] },
  { emoji: '😒', description: 'unamused face', category: 'Smileys & Emotion', aliases: ['unamused'], tags: ['meh'] },
  { emoji: '🙄', description: 'face with rolling eyes', category: 'Smileys & Emotion', aliases: ['roll_eyes'], tags: [] },
  { emoji: '😬', description: 'grimacing face', category: 'Smileys & Emotion', aliases: ['grimacing'], tags: [] },
  { emoji: '🤥', description: 'lying face', category: 'Smileys & Emotion', aliases: ['lying_face'], tags: ['liar'] },
  { emoji: '😌', description: 'relieved face', category: 'Smileys & Emotion', aliases: ['relieved'], tags: ['whew'] },
  { emoji: '😔', description: 'pensive face', category: 'Smileys & Emotion', aliases: ['pensive'], tags: [] },
  { emoji: '😪', description: 'sleepy face', category: 'Smileys & Emotion', aliases: ['sleepy'], tags: ['tired'] },
  { emoji: '🤤', description: 'drooling face', category: 'Smileys & Emotion', aliases: ['drooling_face'], tags: [] },
  { emoji: '😴', description: 'sleeping face', category: 'Smileys & Emotion', aliases: ['sleeping'], tags: ['zzz'] },
  { emoji: '😷', description: 'face with medical mask', category: 'Smileys & Emotion', aliases: ['mask'], tags: ['sick', 'ill'] },
  { emoji: '🤒', description: 'face with thermometer', category: 'Smileys & Emotion', aliases: ['face_with_thermometer'], tags: ['sick'] },
  { emoji: '🤕', description: 'face with head-bandage', category: 'Smileys & Emotion', aliases: ['face_with_head_bandage'], tags: ['hurt'] },
  { emoji: '🤢', description: 'nauseated face', category: 'Smileys & Emotion', aliases: ['nauseated_face'], tags: ['sick', 'barf', 'disgusted'] },
  { emoji: '🤮', description: 'face vomiting', category: 'Smileys & Emotion', aliases: ['vomiting_face'], tags: ['barf', 'sick'] },
  { emoji: '🤧', description: 'sneezing face', category: 'Smileys & Emotion', aliases: ['sneezing_face'], tags: ['achoo', 'sick'] },
  { emoji: '🥵', description: 'hot face', category: 'Smileys & Emotion', aliases: ['hot_face'], tags: ['heat', 'sweating'] },
  { emoji: '🥶', description: 'cold face', category: 'Smileys & Emotion', aliases: ['cold_face'], tags: ['freezing', 'ice'] },
  { emoji: '🥴', description: 'woozy face', category: 'Smileys & Emotion', aliases: ['woozy_face'], tags: ['groggy'] },
  { emoji: '😵', description: 'face with crossed-out eyes', category: 'Smileys & Emotion', aliases: ['dizzy_face'], tags: [] },
  { emoji: '🤯', description: 'exploding head', category: 'Smileys & Emotion', aliases: ['exploding_head'], tags: ['mindblown'] },
  { emoji: '🤠', description: 'cowboy hat face', category: 'Smileys & Emotion', aliases: ['cowboy_hat_face'], tags: [] },
  { emoji: '🥳', description: 'partying face', category: 'Smileys & Emotion', aliases: ['partying_face'], tags: ['celebration', 'birthday'] },
  { emoji: '🥸', description: 'disguised face', category: 'Smileys & Emotion', aliases: ['disguised_face'], tags: [] },
  { emoji: '😎', description: 'smiling face with sunglasses', category: 'Smileys & Emotion', aliases: ['sunglasses'], tags: ['cool'] },
  { emoji: '🤓', description: 'nerd face', category: 'Smileys & Emotion', aliases: ['nerd_face'], tags: ['geek', 'glasses'] },
  { emoji: '🧐', description: 'face with monocle', category: 'Smileys & Emotion', aliases: ['monocle_face'], tags: [] },
  { emoji: '😕', description: 'confused face', category: 'Smileys & Emotion', aliases: ['confused'], tags: [] },
  { emoji: '😟', description: 'worried face', category: 'Smileys & Emotion', aliases: ['worried'], tags: ['nervous'] },
  { emoji: '🙁', description: 'slightly frowning face', category: 'Smileys & Emotion', aliases: ['slightly_frowning_face'], tags: [] },
  { emoji: '☹️', description: 'frowning face', category: 'Smileys & Emotion', aliases: ['frowning_face'], tags: [] },
  { emoji: '😮', description: 'face with open mouth', category: 'Smileys & Emotion', aliases: ['open_mouth'], tags: ['surprise', 'impressed', 'wow'] },
  { emoji: '😯', description: 'hushed face', category: 'Smileys & Emotion', aliases: ['hushed'], tags: ['silence', 'speechless'] },
  { emoji: '😲', description: 'astonished face', category: 'Smileys & Emotion', aliases: ['astonished'], tags: ['amazed', 'gasp'] },
  { emoji: '😳', description: 'flushed face', category: 'Smileys & Emotion', aliases: ['flushed'], tags: [] },
  { emoji: '🥺', description: 'pleading face', category: 'Smileys & Emotion', aliases: ['pleading_face'], tags: ['puppy', 'eyes'] },
  { emoji: '😦', description: 'frowning face with open mouth', category: 'Smileys & Emotion', aliases: ['frowning'], tags: [] },
  { emoji: '😧', description: 'anguished face', category: 'Smileys & Emotion', aliases: ['anguished'], tags: ['stunned'] },
  { emoji: '😨', description: 'fearful face', category: 'Smileys & Emotion', aliases: ['fearful'], tags: ['scared', 'shocked', 'oops'] },
  { emoji: '😰', description: 'anxious face with sweat', category: 'Smileys & Emotion', aliases: ['cold_sweat'], tags: ['nervous'] },
  { emoji: '😥', description: 'sad but relieved face', category: 'Smileys & Emotion', aliases: ['disappointed_relieved'], tags: ['phew', 'sweat', 'nervous'] },
  { emoji: '😢', description: 'crying face', category: 'Smileys & Emotion', aliases: ['cry'], tags: ['sad', 'tear'] },
  { emoji: '😭', description: 'loudly crying face', category: 'Smileys & Emotion', aliases: ['sob'], tags: ['sad', 'cry', 'bawling'] },
  { emoji: '😱', description: 'face screaming in fear', category: 'Smileys & Emotion', aliases: ['scream'], tags: ['horror', 'shocked'] },
  { emoji: '😖', description: 'confounded face', category: 'Smileys & Emotion', aliases: ['confounded'], tags: [] },
  { emoji: '😣', description: 'persevering face', category: 'Smileys & Emotion', aliases: ['persevere'], tags: ['struggling'] },
  { emoji: '😞', description: 'disappointed face', category: 'Smileys & Emotion', aliases: ['disappointed'], tags: ['sad'] },
  { emoji: '😓', description: 'downcast face with sweat', category: 'Smileys & Emotion', aliases: ['sweat'], tags: [] },
  { emoji: '😩', description: 'weary face', category: 'Smileys & Emotion', aliases: ['weary'], tags: ['tired'] },
  { emoji: '😫', description: 'tired face', category: 'Smileys & Emotion', aliases: ['tired_face'], tags: ['upset', 'whine'] },
  { emoji: '🥱', description: 'yawning face', category: 'Smileys & Emotion', aliases: ['yawning_face'], tags: [] },
  { emoji: '😤', description: 'face with steam from nose', category: 'Smileys & Emotion', aliases: ['triumph'], tags: ['smug'] },
  { emoji: '😡', description: 'pouting face', category: 'Smileys & Emotion', aliases: ['rage', 'pout'], tags: ['angry'] },
  { emoji: '😠', description: 'angry face', category: 'Smileys & Emotion', aliases: ['angry'], tags: ['mad', 'annoyed'] },
  { emoji: '🤬', description: 'face with symbols on mouth', category: 'Smileys & Emotion', aliases: ['cursing_face'], tags: ['swearing', 'cursing'] },
  { emoji: '😈', description: 'smiling face with horns', category: 'Smileys & Emotion', aliases: ['smiling_imp'], tags: ['devil', 'evil', 'horns'] },
  { emoji: '👿', description: 'angry face with horns', category: 'Smileys & Emotion', aliases: ['imp'], tags: ['angry', 'devil', 'evil', 'horns'] },
  { emoji: '💀', description: 'skull', category: 'Smileys & Emotion', aliases: ['skull'], tags: ['dead', 'danger', 'poison'] },
  { emoji: '☠️', description: 'skull and crossbones', category: 'Smileys & Emotion', aliases: ['skull_and_crossbones'], tags: ['danger', 'pirate'] },
  { emoji: '💩', description: 'pile of poo', category: 'Smileys & Emotion', aliases: ['hankey', 'poop', 'shit'], tags: ['crap'] },
  { emoji: '🤡', description: 'clown face', category: 'Smileys & Emotion', aliases: ['clown_face'], tags: [] },
  { emoji: '👹', description: 'ogre', category: 'Smileys & Emotion', aliases: ['japanese_ogre'], tags: ['monster'] },
  { emoji: '👺', description: 'goblin', category: 'Smileys & Emotion', aliases: ['japanese_goblin'], tags: [] },
  { emoji: '👻', description: 'ghost', category: 'Smileys & Emotion', aliases: ['ghost'], tags: ['halloween'] },
  { emoji: '👽', description: 'alien', category: 'Smileys & Emotion', aliases: ['alien'], tags: ['ufo'] },
  { emoji: '👾', description: 'alien monster', category: 'Smileys & Emotion', aliases: ['space_invader'], tags: ['game', 'retro'] },
  { emoji: '🤖', description: 'robot', category: 'Smileys & Emotion', aliases: ['robot'], tags: [] },
  { emoji: '😺', description: 'grinning cat', category: 'Smileys & Emotion', aliases: ['smiley_cat'], tags: [] },
  { emoji: '😸', description: 'grinning cat with smiling eyes', category: 'Smileys & Emotion', aliases: ['smile_cat'], tags: [] },
  { emoji: '😹', description: 'cat with tears of joy', category: 'Smileys & Emotion', aliases: ['joy_cat'], tags: [] },
  { emoji: '😻', description: 'smiling cat with heart-eyes', category: 'Smileys & Emotion', aliases: ['heart_eyes_cat'], tags: [] },
  { emoji: '😼', description: 'cat with wry smile', category: 'Smileys & Emotion', aliases: ['smirk_cat'], tags: [] },
  { emoji: '😽', description: 'kissing cat', category: 'Smileys & Emotion', aliases: ['kissing_cat'], tags: [] },
  { emoji: '🙀', description: 'weary cat', category: 'Smileys & Emotion', aliases: ['scream_cat'], tags: ['horror'] },
  { emoji: '😿', description: 'crying cat', category: 'Smileys & Emotion', aliases: ['crying_cat_face'], tags: ['sad', 'tear'] },
  { emoji: '😾', description: 'pouting cat', category: 'Smileys & Emotion', aliases: ['pouting_cat'], tags: [] },

  // Gestures & Body
  { emoji: '👋', description: 'waving hand', category: 'People & Body', aliases: ['wave'], tags: ['goodbye'] },
  { emoji: '🤚', description: 'raised back of hand', category: 'People & Body', aliases: ['raised_back_of_hand'], tags: [] },
  { emoji: '🖐️', description: 'hand with fingers splayed', category: 'People & Body', aliases: ['raised_hand_with_fingers_splayed'], tags: [] },
  { emoji: '✋', description: 'raised hand', category: 'People & Body', aliases: ['hand', 'raised_hand'], tags: ['highfive', 'stop'] },
  { emoji: '🖖', description: 'vulcan salute', category: 'People & Body', aliases: ['vulcan_salute'], tags: ['prosper', 'spock'] },
  { emoji: '👌', description: 'OK hand', category: 'People & Body', aliases: ['ok_hand'], tags: [] },
  { emoji: '🤌', description: 'pinched fingers', category: 'People & Body', aliases: ['pinched_fingers'], tags: ['italian'] },
  { emoji: '🤏', description: 'pinching hand', category: 'People & Body', aliases: ['pinching_hand'], tags: [] },
  { emoji: '✌️', description: 'victory hand', category: 'People & Body', aliases: ['v'], tags: ['victory', 'peace'] },
  { emoji: '🤞', description: 'crossed fingers', category: 'People & Body', aliases: ['crossed_fingers'], tags: ['luck', 'hopeful'] },
  { emoji: '🤟', description: 'love-you gesture', category: 'People & Body', aliases: ['love_you_gesture'], tags: [] },
  { emoji: '🤘', description: 'sign of the horns', category: 'People & Body', aliases: ['metal'], tags: [] },
  { emoji: '🤙', description: 'call me hand', category: 'People & Body', aliases: ['call_me_hand'], tags: [] },
  { emoji: '👈', description: 'backhand index pointing left', category: 'People & Body', aliases: ['point_left'], tags: [] },
  { emoji: '👉', description: 'backhand index pointing right', category: 'People & Body', aliases: ['point_right'], tags: [] },
  { emoji: '👆', description: 'backhand index pointing up', category: 'People & Body', aliases: ['point_up_2'], tags: [] },
  { emoji: '🖕', description: 'middle finger', category: 'People & Body', aliases: ['middle_finger', 'fu'], tags: [] },
  { emoji: '👇', description: 'backhand index pointing down', category: 'People & Body', aliases: ['point_down'], tags: [] },
  { emoji: '☝️', description: 'index pointing up', category: 'People & Body', aliases: ['point_up'], tags: [] },
  { emoji: '👍', description: 'thumbs up', category: 'People & Body', aliases: ['+1', 'thumbsup'], tags: ['approve', 'ok'] },
  { emoji: '👎', description: 'thumbs down', category: 'People & Body', aliases: ['-1', 'thumbsdown'], tags: ['disapprove', 'bury'] },
  { emoji: '✊', description: 'raised fist', category: 'People & Body', aliases: ['fist_raised', 'fist'], tags: ['power'] },
  { emoji: '👊', description: 'oncoming fist', category: 'People & Body', aliases: ['fist_oncoming', 'facepunch', 'punch'], tags: ['attack'] },
  { emoji: '🤛', description: 'left-facing fist', category: 'People & Body', aliases: ['fist_left'], tags: [] },
  { emoji: '🤜', description: 'right-facing fist', category: 'People & Body', aliases: ['fist_right'], tags: [] },
  { emoji: '👏', description: 'clapping hands', category: 'People & Body', aliases: ['clap'], tags: ['praise', 'applause'] },
  { emoji: '🙌', description: 'raising hands', category: 'People & Body', aliases: ['raised_hands'], tags: ['hooray'] },
  { emoji: '👐', description: 'open hands', category: 'People & Body', aliases: ['open_hands'], tags: [] },
  { emoji: '🤲', description: 'palms up together', category: 'People & Body', aliases: ['palms_up_together'], tags: [] },
  { emoji: '🤝', description: 'handshake', category: 'People & Body', aliases: ['handshake'], tags: ['deal'] },
  { emoji: '🙏', description: 'folded hands', category: 'People & Body', aliases: ['pray'], tags: ['please', 'hope', 'wish'] },
  { emoji: '✍️', description: 'writing hand', category: 'People & Body', aliases: ['writing_hand'], tags: [] },
  { emoji: '💪', description: 'flexed biceps', category: 'People & Body', aliases: ['muscle'], tags: ['flex', 'bicep', 'strong', 'workout'] },

  // Hearts & Love
  { emoji: '❤️', description: 'red heart', category: 'Smileys & Emotion', aliases: ['heart'], tags: ['love'] },
  { emoji: '🧡', description: 'orange heart', category: 'Smileys & Emotion', aliases: ['orange_heart'], tags: [] },
  { emoji: '💛', description: 'yellow heart', category: 'Smileys & Emotion', aliases: ['yellow_heart'], tags: [] },
  { emoji: '💚', description: 'green heart', category: 'Smileys & Emotion', aliases: ['green_heart'], tags: [] },
  { emoji: '💙', description: 'blue heart', category: 'Smileys & Emotion', aliases: ['blue_heart'], tags: [] },
  { emoji: '💜', description: 'purple heart', category: 'Smileys & Emotion', aliases: ['purple_heart'], tags: [] },
  { emoji: '🖤', description: 'black heart', category: 'Smileys & Emotion', aliases: ['black_heart'], tags: [] },
  { emoji: '🤍', description: 'white heart', category: 'Smileys & Emotion', aliases: ['white_heart'], tags: [] },
  { emoji: '🤎', description: 'brown heart', category: 'Smileys & Emotion', aliases: ['brown_heart'], tags: [] },
  { emoji: '💔', description: 'broken heart', category: 'Smileys & Emotion', aliases: ['broken_heart'], tags: [] },
  { emoji: '❣️', description: 'heart exclamation', category: 'Smileys & Emotion', aliases: ['heavy_heart_exclamation'], tags: [] },
  { emoji: '💕', description: 'two hearts', category: 'Smileys & Emotion', aliases: ['two_hearts'], tags: [] },
  { emoji: '💞', description: 'revolving hearts', category: 'Smileys & Emotion', aliases: ['revolving_hearts'], tags: [] },
  { emoji: '💓', description: 'beating heart', category: 'Smileys & Emotion', aliases: ['heartbeat'], tags: [] },
  { emoji: '💗', description: 'growing heart', category: 'Smileys & Emotion', aliases: ['heartpulse'], tags: [] },
  { emoji: '💖', description: 'sparkling heart', category: 'Smileys & Emotion', aliases: ['sparkling_heart'], tags: [] },
  { emoji: '💘', description: 'heart with arrow', category: 'Smileys & Emotion', aliases: ['cupid'], tags: ['love', 'heart'] },
  { emoji: '💝', description: 'heart with ribbon', category: 'Smileys & Emotion', aliases: ['gift_heart'], tags: ['chocolates'] },
  { emoji: '💟', description: 'heart decoration', category: 'Smileys & Emotion', aliases: ['heart_decoration'], tags: [] },
  { emoji: '💌', description: 'love letter', category: 'Smileys & Emotion', aliases: ['love_letter'], tags: ['email', 'envelope'] },
  { emoji: '💋', description: 'kiss mark', category: 'Smileys & Emotion', aliases: ['kiss'], tags: ['lipstick'] },
  { emoji: '💯', description: 'hundred points', category: 'Smileys & Emotion', aliases: ['100'], tags: ['score', 'perfect'] },
  { emoji: '💢', description: 'anger symbol', category: 'Smileys & Emotion', aliases: ['anger'], tags: ['angry'] },
  { emoji: '💥', description: 'collision', category: 'Smileys & Emotion', aliases: ['boom', 'collision'], tags: ['explode'] },
  { emoji: '💫', description: 'dizzy', category: 'Smileys & Emotion', aliases: ['dizzy'], tags: ['star'] },
  { emoji: '💦', description: 'sweat droplets', category: 'Smileys & Emotion', aliases: ['sweat_drops'], tags: ['water', 'workout'] },
  { emoji: '💨', description: 'dashing away', category: 'Smileys & Emotion', aliases: ['dash'], tags: ['wind', 'blow', 'fast'] },
  { emoji: '🕳️', description: 'hole', category: 'Smileys & Emotion', aliases: ['hole'], tags: [] },
  { emoji: '💣', description: 'bomb', category: 'Smileys & Emotion', aliases: ['bomb'], tags: ['boom'] },
  { emoji: '💬', description: 'speech balloon', category: 'Smileys & Emotion', aliases: ['speech_balloon'], tags: ['comment'] },
  { emoji: '💭', description: 'thought balloon', category: 'Smileys & Emotion', aliases: ['thought_balloon'], tags: ['thinking'] },
  { emoji: '💤', description: 'zzz', category: 'Smileys & Emotion', aliases: ['zzz'], tags: ['sleeping'] },

  // Animals & Nature
  { emoji: '🐶', description: 'dog face', category: 'Animals & Nature', aliases: ['dog'], tags: ['pet'] },
  { emoji: '🐱', description: 'cat face', category: 'Animals & Nature', aliases: ['cat'], tags: ['pet'] },
  { emoji: '🐭', description: 'mouse face', category: 'Animals & Nature', aliases: ['mouse'], tags: [] },
  { emoji: '🐹', description: 'hamster', category: 'Animals & Nature', aliases: ['hamster'], tags: ['pet'] },
  { emoji: '🐰', description: 'rabbit face', category: 'Animals & Nature', aliases: ['rabbit'], tags: ['bunny'] },
  { emoji: '🦊', description: 'fox', category: 'Animals & Nature', aliases: ['fox_face'], tags: [] },
  { emoji: '🐻', description: 'bear', category: 'Animals & Nature', aliases: ['bear'], tags: [] },
  { emoji: '🐼', description: 'panda', category: 'Animals & Nature', aliases: ['panda_face'], tags: [] },
  { emoji: '🐨', description: 'koala', category: 'Animals & Nature', aliases: ['koala'], tags: [] },
  { emoji: '🐯', description: 'tiger face', category: 'Animals & Nature', aliases: ['tiger'], tags: [] },
  { emoji: '🦁', description: 'lion', category: 'Animals & Nature', aliases: ['lion'], tags: [] },
  { emoji: '🐮', description: 'cow face', category: 'Animals & Nature', aliases: ['cow'], tags: [] },
  { emoji: '🐷', description: 'pig face', category: 'Animals & Nature', aliases: ['pig'], tags: [] },
  { emoji: '🐸', description: 'frog', category: 'Animals & Nature', aliases: ['frog'], tags: [] },
  { emoji: '🐵', description: 'monkey face', category: 'Animals & Nature', aliases: ['monkey_face'], tags: [] },
  { emoji: '🙈', description: 'see-no-evil monkey', category: 'Animals & Nature', aliases: ['see_no_evil'], tags: ['monkey', 'blind', 'ignore'] },
  { emoji: '🙉', description: 'hear-no-evil monkey', category: 'Animals & Nature', aliases: ['hear_no_evil'], tags: ['monkey', 'deaf'] },
  { emoji: '🙊', description: 'speak-no-evil monkey', category: 'Animals & Nature', aliases: ['speak_no_evil'], tags: ['monkey', 'mute', 'hush'] },
  { emoji: '🐔', description: 'chicken', category: 'Animals & Nature', aliases: ['chicken'], tags: [] },
  { emoji: '🐧', description: 'penguin', category: 'Animals & Nature', aliases: ['penguin'], tags: [] },
  { emoji: '🐦', description: 'bird', category: 'Animals & Nature', aliases: ['bird'], tags: [] },
  { emoji: '🐤', description: 'baby chick', category: 'Animals & Nature', aliases: ['baby_chick'], tags: [] },
  { emoji: '🦆', description: 'duck', category: 'Animals & Nature', aliases: ['duck'], tags: [] },
  { emoji: '🦅', description: 'eagle', category: 'Animals & Nature', aliases: ['eagle'], tags: [] },
  { emoji: '🦉', description: 'owl', category: 'Animals & Nature', aliases: ['owl'], tags: [] },
  { emoji: '🦇', description: 'bat', category: 'Animals & Nature', aliases: ['bat'], tags: [] },
  { emoji: '🐺', description: 'wolf', category: 'Animals & Nature', aliases: ['wolf'], tags: [] },
  { emoji: '🐗', description: 'boar', category: 'Animals & Nature', aliases: ['boar'], tags: [] },
  { emoji: '🐴', description: 'horse face', category: 'Animals & Nature', aliases: ['horse'], tags: [] },
  { emoji: '🦄', description: 'unicorn', category: 'Animals & Nature', aliases: ['unicorn'], tags: [] },
  { emoji: '🐝', description: 'honeybee', category: 'Animals & Nature', aliases: ['bee', 'honeybee'], tags: [] },
  { emoji: '🐛', description: 'bug', category: 'Animals & Nature', aliases: ['bug'], tags: [] },
  { emoji: '🦋', description: 'butterfly', category: 'Animals & Nature', aliases: ['butterfly'], tags: [] },
  { emoji: '🐌', description: 'snail', category: 'Animals & Nature', aliases: ['snail'], tags: ['slow'] },
  { emoji: '🐞', description: 'lady beetle', category: 'Animals & Nature', aliases: ['lady_beetle'], tags: ['bug'] },
  { emoji: '🐜', description: 'ant', category: 'Animals & Nature', aliases: ['ant'], tags: [] },
  { emoji: '🦟', description: 'mosquito', category: 'Animals & Nature', aliases: ['mosquito'], tags: [] },
  { emoji: '🐢', description: 'turtle', category: 'Animals & Nature', aliases: ['turtle'], tags: ['slow'] },
  { emoji: '🐍', description: 'snake', category: 'Animals & Nature', aliases: ['snake'], tags: [] },
  { emoji: '🦎', description: 'lizard', category: 'Animals & Nature', aliases: ['lizard'], tags: [] },
  { emoji: '🦂', description: 'scorpion', category: 'Animals & Nature', aliases: ['scorpion'], tags: [] },
  { emoji: '🦀', description: 'crab', category: 'Animals & Nature', aliases: ['crab'], tags: [] },
  { emoji: '🦑', description: 'squid', category: 'Animals & Nature', aliases: ['squid'], tags: [] },
  { emoji: '🐙', description: 'octopus', category: 'Animals & Nature', aliases: ['octopus'], tags: [] },
  { emoji: '🦐', description: 'shrimp', category: 'Animals & Nature', aliases: ['shrimp'], tags: [] },
  { emoji: '🐠', description: 'tropical fish', category: 'Animals & Nature', aliases: ['tropical_fish'], tags: [] },
  { emoji: '🐟', description: 'fish', category: 'Animals & Nature', aliases: ['fish'], tags: [] },
  { emoji: '🐡', description: 'blowfish', category: 'Animals & Nature', aliases: ['blowfish'], tags: [] },
  { emoji: '🐬', description: 'dolphin', category: 'Animals & Nature', aliases: ['dolphin', 'flipper'], tags: [] },
  { emoji: '🦈', description: 'shark', category: 'Animals & Nature', aliases: ['shark'], tags: [] },
  { emoji: '🐳', description: 'spouting whale', category: 'Animals & Nature', aliases: ['whale'], tags: ['sea'] },
  { emoji: '🐋', description: 'whale', category: 'Animals & Nature', aliases: ['whale2'], tags: [] },
  { emoji: '🐊', description: 'crocodile', category: 'Animals & Nature', aliases: ['crocodile'], tags: [] },
  { emoji: '🐆', description: 'leopard', category: 'Animals & Nature', aliases: ['leopard'], tags: [] },
  { emoji: '🐅', description: 'tiger', category: 'Animals & Nature', aliases: ['tiger2'], tags: [] },
  { emoji: '🐃', description: 'water buffalo', category: 'Animals & Nature', aliases: ['water_buffalo'], tags: [] },
  { emoji: '🐂', description: 'ox', category: 'Animals & Nature', aliases: ['ox'], tags: [] },
  { emoji: '🐄', description: 'cow', category: 'Animals & Nature', aliases: ['cow2'], tags: [] },
  { emoji: '🐪', description: 'camel', category: 'Animals & Nature', aliases: ['dromedary_camel'], tags: ['desert'] },
  { emoji: '🐫', description: 'two-hump camel', category: 'Animals & Nature', aliases: ['camel'], tags: [] },
  { emoji: '🦙', description: 'llama', category: 'Animals & Nature', aliases: ['llama'], tags: [] },
  { emoji: '🦒', description: 'giraffe', category: 'Animals & Nature', aliases: ['giraffe'], tags: [] },
  { emoji: '🐘', description: 'elephant', category: 'Animals & Nature', aliases: ['elephant'], tags: [] },
  { emoji: '🦏', description: 'rhinoceros', category: 'Animals & Nature', aliases: ['rhinoceros'], tags: [] },
  { emoji: '🦛', description: 'hippopotamus', category: 'Animals & Nature', aliases: ['hippopotamus'], tags: [] },
  { emoji: '🐁', description: 'mouse', category: 'Animals & Nature', aliases: ['mouse2'], tags: [] },
  { emoji: '🐀', description: 'rat', category: 'Animals & Nature', aliases: ['rat'], tags: [] },
  { emoji: '🐿️', description: 'chipmunk', category: 'Animals & Nature', aliases: ['chipmunk'], tags: [] },
  { emoji: '🦔', description: 'hedgehog', category: 'Animals & Nature', aliases: ['hedgehog'], tags: [] },
  { emoji: '🐕', description: 'dog', category: 'Animals & Nature', aliases: ['dog2'], tags: [] },
  { emoji: '🐩', description: 'poodle', category: 'Animals & Nature', aliases: ['poodle'], tags: ['dog'] },
  { emoji: '🐈', description: 'cat', category: 'Animals & Nature', aliases: ['cat2'], tags: [] },
  { emoji: '🐓', description: 'rooster', category: 'Animals & Nature', aliases: ['rooster'], tags: [] },
  { emoji: '🦃', description: 'turkey', category: 'Animals & Nature', aliases: ['turkey'], tags: ['thanksgiving'] },
  { emoji: '🦚', description: 'peacock', category: 'Animals & Nature', aliases: ['peacock'], tags: [] },
  { emoji: '🦜', description: 'parrot', category: 'Animals & Nature', aliases: ['parrot'], tags: [] },
  { emoji: '🦢', description: 'swan', category: 'Animals & Nature', aliases: ['swan'], tags: [] },
  { emoji: '🦩', description: 'flamingo', category: 'Animals & Nature', aliases: ['flamingo'], tags: [] },
  { emoji: '🕊️', description: 'dove', category: 'Animals & Nature', aliases: ['dove'], tags: ['peace'] },
  { emoji: '🐇', description: 'rabbit', category: 'Animals & Nature', aliases: ['rabbit2'], tags: [] },
  { emoji: '🦝', description: 'raccoon', category: 'Animals & Nature', aliases: ['raccoon'], tags: [] },
  { emoji: '🦨', description: 'skunk', category: 'Animals & Nature', aliases: ['skunk'], tags: [] },
  { emoji: '🦡', description: 'badger', category: 'Animals & Nature', aliases: ['badger'], tags: [] },
  { emoji: '🦦', description: 'otter', category: 'Animals & Nature', aliases: ['otter'], tags: [] },
  { emoji: '🦥', description: 'sloth', category: 'Animals & Nature', aliases: ['sloth'], tags: [] },
  { emoji: '🐉', description: 'dragon', category: 'Animals & Nature', aliases: ['dragon'], tags: [] },
  { emoji: '🐲', description: 'dragon face', category: 'Animals & Nature', aliases: ['dragon_face'], tags: [] },

  // Plants
  { emoji: '🌵', description: 'cactus', category: 'Animals & Nature', aliases: ['cactus'], tags: [] },
  { emoji: '🎄', description: 'Christmas tree', category: 'Animals & Nature', aliases: ['christmas_tree'], tags: [] },
  { emoji: '🌲', description: 'evergreen tree', category: 'Animals & Nature', aliases: ['evergreen_tree'], tags: ['wood'] },
  { emoji: '🌳', description: 'deciduous tree', category: 'Animals & Nature', aliases: ['deciduous_tree'], tags: ['wood'] },
  { emoji: '🌴', description: 'palm tree', category: 'Animals & Nature', aliases: ['palm_tree'], tags: [] },
  { emoji: '🌱', description: 'seedling', category: 'Animals & Nature', aliases: ['seedling'], tags: ['plant'] },
  { emoji: '🌿', description: 'herb', category: 'Animals & Nature', aliases: ['herb'], tags: [] },
  { emoji: '☘️', description: 'shamrock', category: 'Animals & Nature', aliases: ['shamrock'], tags: [] },
  { emoji: '🍀', description: 'four leaf clover', category: 'Animals & Nature', aliases: ['four_leaf_clover'], tags: ['luck'] },
  { emoji: '🎋', description: 'tanabata tree', category: 'Animals & Nature', aliases: ['tanabata_tree'], tags: [] },
  { emoji: '🎍', description: 'pine decoration', category: 'Animals & Nature', aliases: ['bamboo'], tags: [] },
  { emoji: '🍃', description: 'leaf fluttering in wind', category: 'Animals & Nature', aliases: ['leaves'], tags: ['leaf'] },
  { emoji: '🍂', description: 'fallen leaf', category: 'Animals & Nature', aliases: ['fallen_leaf'], tags: ['autumn'] },
  { emoji: '🍁', description: 'maple leaf', category: 'Animals & Nature', aliases: ['maple_leaf'], tags: ['canada'] },
  { emoji: '🌾', description: 'sheaf of rice', category: 'Animals & Nature', aliases: ['ear_of_rice'], tags: [] },
  { emoji: '🌺', description: 'hibiscus', category: 'Animals & Nature', aliases: ['hibiscus'], tags: [] },
  { emoji: '🌻', description: 'sunflower', category: 'Animals & Nature', aliases: ['sunflower'], tags: [] },
  { emoji: '🌹', description: 'rose', category: 'Animals & Nature', aliases: ['rose'], tags: ['flower'] },
  { emoji: '🥀', description: 'wilted flower', category: 'Animals & Nature', aliases: ['wilted_flower'], tags: [] },
  { emoji: '🌷', description: 'tulip', category: 'Animals & Nature', aliases: ['tulip'], tags: ['flower'] },
  { emoji: '🌼', description: 'blossom', category: 'Animals & Nature', aliases: ['blossom'], tags: [] },
  { emoji: '🌸', description: 'cherry blossom', category: 'Animals & Nature', aliases: ['cherry_blossom'], tags: ['flower', 'spring'] },
  { emoji: '💐', description: 'bouquet', category: 'Animals & Nature', aliases: ['bouquet'], tags: ['flowers'] },
  { emoji: '🍄', description: 'mushroom', category: 'Animals & Nature', aliases: ['mushroom'], tags: [] },

  // Food & Drink
  { emoji: '🍎', description: 'red apple', category: 'Food & Drink', aliases: ['apple'], tags: [] },
  { emoji: '🍐', description: 'pear', category: 'Food & Drink', aliases: ['pear'], tags: [] },
  { emoji: '🍊', description: 'tangerine', category: 'Food & Drink', aliases: ['tangerine', 'orange', 'mandarin'], tags: [] },
  { emoji: '🍋', description: 'lemon', category: 'Food & Drink', aliases: ['lemon'], tags: [] },
  { emoji: '🍌', description: 'banana', category: 'Food & Drink', aliases: ['banana'], tags: ['fruit'] },
  { emoji: '🍉', description: 'watermelon', category: 'Food & Drink', aliases: ['watermelon'], tags: [] },
  { emoji: '🍇', description: 'grapes', category: 'Food & Drink', aliases: ['grapes'], tags: [] },
  { emoji: '🍓', description: 'strawberry', category: 'Food & Drink', aliases: ['strawberry'], tags: ['fruit'] },
  { emoji: '🍈', description: 'melon', category: 'Food & Drink', aliases: ['melon'], tags: [] },
  { emoji: '🍒', description: 'cherries', category: 'Food & Drink', aliases: ['cherries'], tags: ['fruit'] },
  { emoji: '🍑', description: 'peach', category: 'Food & Drink', aliases: ['peach'], tags: [] },
  { emoji: '🥭', description: 'mango', category: 'Food & Drink', aliases: ['mango'], tags: [] },
  { emoji: '🍍', description: 'pineapple', category: 'Food & Drink', aliases: ['pineapple'], tags: [] },
  { emoji: '🥥', description: 'coconut', category: 'Food & Drink', aliases: ['coconut'], tags: [] },
  { emoji: '🥝', description: 'kiwi fruit', category: 'Food & Drink', aliases: ['kiwi_fruit'], tags: [] },
  { emoji: '🍅', description: 'tomato', category: 'Food & Drink', aliases: ['tomato'], tags: [] },
  { emoji: '🍆', description: 'eggplant', category: 'Food & Drink', aliases: ['eggplant'], tags: ['aubergine'] },
  { emoji: '🥑', description: 'avocado', category: 'Food & Drink', aliases: ['avocado'], tags: [] },
  { emoji: '🥦', description: 'broccoli', category: 'Food & Drink', aliases: ['broccoli'], tags: [] },
  { emoji: '🥬', description: 'leafy green', category: 'Food & Drink', aliases: ['leafy_green'], tags: [] },
  { emoji: '🥒', description: 'cucumber', category: 'Food & Drink', aliases: ['cucumber'], tags: [] },
  { emoji: '🌶️', description: 'hot pepper', category: 'Food & Drink', aliases: ['hot_pepper'], tags: ['spicy'] },
  { emoji: '🌽', description: 'ear of corn', category: 'Food & Drink', aliases: ['corn'], tags: [] },
  { emoji: '🥕', description: 'carrot', category: 'Food & Drink', aliases: ['carrot'], tags: [] },
  { emoji: '🥔', description: 'potato', category: 'Food & Drink', aliases: ['potato'], tags: [] },
  { emoji: '🍠', description: 'roasted sweet potato', category: 'Food & Drink', aliases: ['sweet_potato'], tags: [] },
  { emoji: '🥐', description: 'croissant', category: 'Food & Drink', aliases: ['croissant'], tags: [] },
  { emoji: '🍞', description: 'bread', category: 'Food & Drink', aliases: ['bread'], tags: ['toast'] },
  { emoji: '🥖', description: 'baguette bread', category: 'Food & Drink', aliases: ['baguette_bread'], tags: [] },
  { emoji: '🥨', description: 'pretzel', category: 'Food & Drink', aliases: ['pretzel'], tags: [] },
  { emoji: '🧀', description: 'cheese wedge', category: 'Food & Drink', aliases: ['cheese'], tags: [] },
  { emoji: '🥚', description: 'egg', category: 'Food & Drink', aliases: ['egg'], tags: [] },
  { emoji: '🍳', description: 'cooking', category: 'Food & Drink', aliases: ['fried_egg'], tags: ['breakfast'] },
  { emoji: '🥞', description: 'pancakes', category: 'Food & Drink', aliases: ['pancakes'], tags: [] },
  { emoji: '🧇', description: 'waffle', category: 'Food & Drink', aliases: ['waffle'], tags: [] },
  { emoji: '🥓', description: 'bacon', category: 'Food & Drink', aliases: ['bacon'], tags: [] },
  { emoji: '🥩', description: 'cut of meat', category: 'Food & Drink', aliases: ['cut_of_meat'], tags: [] },
  { emoji: '🍗', description: 'poultry leg', category: 'Food & Drink', aliases: ['poultry_leg'], tags: ['meat', 'chicken'] },
  { emoji: '🍖', description: 'meat on bone', category: 'Food & Drink', aliases: ['meat_on_bone'], tags: [] },
  { emoji: '🌭', description: 'hot dog', category: 'Food & Drink', aliases: ['hotdog'], tags: [] },
  { emoji: '🍔', description: 'hamburger', category: 'Food & Drink', aliases: ['hamburger'], tags: ['burger'] },
  { emoji: '🍟', description: 'french fries', category: 'Food & Drink', aliases: ['fries'], tags: [] },
  { emoji: '🍕', description: 'pizza', category: 'Food & Drink', aliases: ['pizza'], tags: [] },
  { emoji: '🥪', description: 'sandwich', category: 'Food & Drink', aliases: ['sandwich'], tags: [] },
  { emoji: '🥙', description: 'stuffed flatbread', category: 'Food & Drink', aliases: ['stuffed_flatbread'], tags: [] },
  { emoji: '🌮', description: 'taco', category: 'Food & Drink', aliases: ['taco'], tags: [] },
  { emoji: '🌯', description: 'burrito', category: 'Food & Drink', aliases: ['burrito'], tags: [] },
  { emoji: '🥗', description: 'green salad', category: 'Food & Drink', aliases: ['green_salad'], tags: ['healthy'] },
  { emoji: '🥘', description: 'shallow pan of food', category: 'Food & Drink', aliases: ['shallow_pan_of_food'], tags: ['paella', 'curry'] },
  { emoji: '🍝', description: 'spaghetti', category: 'Food & Drink', aliases: ['spaghetti'], tags: ['pasta'] },
  { emoji: '🍜', description: 'steaming bowl', category: 'Food & Drink', aliases: ['ramen'], tags: ['noodle'] },
  { emoji: '🍲', description: 'pot of food', category: 'Food & Drink', aliases: ['stew'], tags: [] },
  { emoji: '🍛', description: 'curry rice', category: 'Food & Drink', aliases: ['curry'], tags: [] },
  { emoji: '🍣', description: 'sushi', category: 'Food & Drink', aliases: ['sushi'], tags: [] },
  { emoji: '🍱', description: 'bento box', category: 'Food & Drink', aliases: ['bento'], tags: [] },
  { emoji: '🥟', description: 'dumpling', category: 'Food & Drink', aliases: ['dumpling'], tags: [] },
  { emoji: '🍤', description: 'fried shrimp', category: 'Food & Drink', aliases: ['fried_shrimp'], tags: ['tempura'] },
  { emoji: '🍙', description: 'rice ball', category: 'Food & Drink', aliases: ['rice_ball'], tags: [] },
  { emoji: '🍚', description: 'cooked rice', category: 'Food & Drink', aliases: ['rice'], tags: [] },
  { emoji: '🍘', description: 'rice cracker', category: 'Food & Drink', aliases: ['rice_cracker'], tags: [] },
  { emoji: '🍥', description: 'fish cake with swirl', category: 'Food & Drink', aliases: ['fish_cake'], tags: [] },
  { emoji: '🥠', description: 'fortune cookie', category: 'Food & Drink', aliases: ['fortune_cookie'], tags: [] },
  { emoji: '🥮', description: 'moon cake', category: 'Food & Drink', aliases: ['moon_cake'], tags: [] },
  { emoji: '🍢', description: 'oden', category: 'Food & Drink', aliases: ['oden'], tags: [] },
  { emoji: '🍡', description: 'dango', category: 'Food & Drink', aliases: ['dango'], tags: [] },
  { emoji: '🍧', description: 'shaved ice', category: 'Food & Drink', aliases: ['shaved_ice'], tags: [] },
  { emoji: '🍨', description: 'ice cream', category: 'Food & Drink', aliases: ['ice_cream'], tags: [] },
  { emoji: '🍦', description: 'soft ice cream', category: 'Food & Drink', aliases: ['icecream'], tags: [] },
  { emoji: '🥧', description: 'pie', category: 'Food & Drink', aliases: ['pie'], tags: [] },
  { emoji: '🧁', description: 'cupcake', category: 'Food & Drink', aliases: ['cupcake'], tags: [] },
  { emoji: '🍰', description: 'shortcake', category: 'Food & Drink', aliases: ['cake'], tags: ['dessert'] },
  { emoji: '🎂', description: 'birthday cake', category: 'Food & Drink', aliases: ['birthday'], tags: ['party'] },
  { emoji: '🍮', description: 'custard', category: 'Food & Drink', aliases: ['custard'], tags: [] },
  { emoji: '🍭', description: 'lollipop', category: 'Food & Drink', aliases: ['lollipop'], tags: [] },
  { emoji: '🍬', description: 'candy', category: 'Food & Drink', aliases: ['candy'], tags: ['sweet'] },
  { emoji: '🍫', description: 'chocolate bar', category: 'Food & Drink', aliases: ['chocolate_bar'], tags: [] },
  { emoji: '🍿', description: 'popcorn', category: 'Food & Drink', aliases: ['popcorn'], tags: [] },
  { emoji: '🍩', description: 'doughnut', category: 'Food & Drink', aliases: ['doughnut'], tags: [] },
  { emoji: '🍪', description: 'cookie', category: 'Food & Drink', aliases: ['cookie'], tags: [] },
  { emoji: '🌰', description: 'chestnut', category: 'Food & Drink', aliases: ['chestnut'], tags: [] },
  { emoji: '🥜', description: 'peanuts', category: 'Food & Drink', aliases: ['peanuts'], tags: [] },
  { emoji: '🍯', description: 'honey pot', category: 'Food & Drink', aliases: ['honey_pot'], tags: [] },
  { emoji: '🥛', description: 'glass of milk', category: 'Food & Drink', aliases: ['milk_glass'], tags: [] },
  { emoji: '🍼', description: 'baby bottle', category: 'Food & Drink', aliases: ['baby_bottle'], tags: ['milk'] },
  { emoji: '☕', description: 'hot beverage', category: 'Food & Drink', aliases: ['coffee'], tags: ['cafe', 'espresso'] },
  { emoji: '🍵', description: 'teacup without handle', category: 'Food & Drink', aliases: ['tea'], tags: ['green', 'breakfast'] },
  { emoji: '🧃', description: 'beverage box', category: 'Food & Drink', aliases: ['beverage_box'], tags: [] },
  { emoji: '🥤', description: 'cup with straw', category: 'Food & Drink', aliases: ['cup_with_straw'], tags: [] },
  { emoji: '🧋', description: 'bubble tea', category: 'Food & Drink', aliases: ['bubble_tea'], tags: ['boba'] },
  { emoji: '🍶', description: 'sake', category: 'Food & Drink', aliases: ['sake'], tags: [] },
  { emoji: '🍺', description: 'beer mug', category: 'Food & Drink', aliases: ['beer'], tags: ['drink'] },
  { emoji: '🍻', description: 'clinking beer mugs', category: 'Food & Drink', aliases: ['beers'], tags: ['drinks'] },
  { emoji: '🥂', description: 'clinking glasses', category: 'Food & Drink', aliases: ['clinking_glasses'], tags: ['cheers', 'toast'] },
  { emoji: '🍷', description: 'wine glass', category: 'Food & Drink', aliases: ['wine_glass'], tags: [] },
  { emoji: '🥃', description: 'tumbler glass', category: 'Food & Drink', aliases: ['tumbler_glass'], tags: ['whisky'] },
  { emoji: '🍸', description: 'cocktail glass', category: 'Food & Drink', aliases: ['cocktail'], tags: ['drink'] },
  { emoji: '🍹', description: 'tropical drink', category: 'Food & Drink', aliases: ['tropical_drink'], tags: ['summer', 'vacation'] },
  { emoji: '🧊', description: 'ice', category: 'Food & Drink', aliases: ['ice_cube'], tags: [] },
  { emoji: '🍴', description: 'fork and knife', category: 'Food & Drink', aliases: ['fork_and_knife'], tags: ['cutlery'] },

  // Activities
  { emoji: '⚽', description: 'soccer ball', category: 'Activities', aliases: ['soccer'], tags: ['sports'] },
  { emoji: '🏀', description: 'basketball', category: 'Activities', aliases: ['basketball'], tags: ['sports'] },
  { emoji: '🏈', description: 'american football', category: 'Activities', aliases: ['football'], tags: ['sports'] },
  { emoji: '⚾', description: 'baseball', category: 'Activities', aliases: ['baseball'], tags: ['sports'] },
  { emoji: '🥎', description: 'softball', category: 'Activities', aliases: ['softball'], tags: [] },
  { emoji: '🎾', description: 'tennis', category: 'Activities', aliases: ['tennis'], tags: ['sports'] },
  { emoji: '🏐', description: 'volleyball', category: 'Activities', aliases: ['volleyball'], tags: [] },
  { emoji: '🏉', description: 'rugby football', category: 'Activities', aliases: ['rugby_football'], tags: [] },
  { emoji: '🥏', description: 'flying disc', category: 'Activities', aliases: ['flying_disc'], tags: [] },
  { emoji: '🎱', description: 'pool 8 ball', category: 'Activities', aliases: ['8ball'], tags: ['billiards'] },
  { emoji: '🪀', description: 'yo-yo', category: 'Activities', aliases: ['yo_yo'], tags: [] },
  { emoji: '🏓', description: 'ping pong', category: 'Activities', aliases: ['ping_pong'], tags: [] },
  { emoji: '🏸', description: 'badminton', category: 'Activities', aliases: ['badminton'], tags: [] },
  { emoji: '🏒', description: 'ice hockey', category: 'Activities', aliases: ['ice_hockey'], tags: [] },
  { emoji: '🏑', description: 'field hockey', category: 'Activities', aliases: ['field_hockey'], tags: [] },
  { emoji: '🥍', description: 'lacrosse', category: 'Activities', aliases: ['lacrosse'], tags: [] },
  { emoji: '🏏', description: 'cricket game', category: 'Activities', aliases: ['cricket_game'], tags: [] },
  { emoji: '🥅', description: 'goal net', category: 'Activities', aliases: ['goal_net'], tags: [] },
  { emoji: '⛳', description: 'flag in hole', category: 'Activities', aliases: ['golf'], tags: [] },
  { emoji: '🪁', description: 'kite', category: 'Activities', aliases: ['kite'], tags: [] },
  { emoji: '🎣', description: 'fishing pole', category: 'Activities', aliases: ['fishing_pole_and_fish'], tags: [] },
  { emoji: '🤿', description: 'diving mask', category: 'Activities', aliases: ['diving_mask'], tags: [] },
  { emoji: '🎽', description: 'running shirt', category: 'Activities', aliases: ['running_shirt_with_sash'], tags: ['marathon'] },
  { emoji: '🎿', description: 'skis', category: 'Activities', aliases: ['ski'], tags: [] },
  { emoji: '🛷', description: 'sled', category: 'Activities', aliases: ['sled'], tags: [] },
  { emoji: '🥌', description: 'curling stone', category: 'Activities', aliases: ['curling_stone'], tags: [] },
  { emoji: '🎯', description: 'direct hit', category: 'Activities', aliases: ['dart'], tags: ['target'] },
  { emoji: '🪃', description: 'boomerang', category: 'Activities', aliases: ['boomerang'], tags: [] },
  { emoji: '🎮', description: 'video game', category: 'Activities', aliases: ['video_game'], tags: ['play', 'controller', 'console'] },
  { emoji: '🕹️', description: 'joystick', category: 'Activities', aliases: ['joystick'], tags: [] },
  { emoji: '🎲', description: 'game die', category: 'Activities', aliases: ['game_die'], tags: ['dice', 'gambling'] },
  { emoji: '🧩', description: 'puzzle piece', category: 'Activities', aliases: ['jigsaw'], tags: [] },
  { emoji: '🎰', description: 'slot machine', category: 'Activities', aliases: ['slot_machine'], tags: [] },
  { emoji: '🎳', description: 'bowling', category: 'Activities', aliases: ['bowling'], tags: [] },

  // Objects
  { emoji: '⌚', description: 'watch', category: 'Objects', aliases: ['watch'], tags: ['time'] },
  { emoji: '📱', description: 'mobile phone', category: 'Objects', aliases: ['iphone'], tags: ['smartphone', 'mobile'] },
  { emoji: '💻', description: 'laptop', category: 'Objects', aliases: ['computer'], tags: ['desktop', 'screen'] },
  { emoji: '⌨️', description: 'keyboard', category: 'Objects', aliases: ['keyboard'], tags: [] },
  { emoji: '🖥️', description: 'desktop computer', category: 'Objects', aliases: ['desktop_computer'], tags: [] },
  { emoji: '🖨️', description: 'printer', category: 'Objects', aliases: ['printer'], tags: [] },
  { emoji: '🖱️', description: 'computer mouse', category: 'Objects', aliases: ['computer_mouse'], tags: [] },
  { emoji: '💽', description: 'computer disk', category: 'Objects', aliases: ['minidisc'], tags: [] },
  { emoji: '💾', description: 'floppy disk', category: 'Objects', aliases: ['floppy_disk'], tags: ['save'] },
  { emoji: '💿', description: 'optical disk', category: 'Objects', aliases: ['cd'], tags: [] },
  { emoji: '📀', description: 'dvd', category: 'Objects', aliases: ['dvd'], tags: [] },
  { emoji: '🎥', description: 'movie camera', category: 'Objects', aliases: ['movie_camera'], tags: ['film', 'video'] },
  { emoji: '📷', description: 'camera', category: 'Objects', aliases: ['camera'], tags: ['photo'] },
  { emoji: '📹', description: 'video camera', category: 'Objects', aliases: ['video_camera'], tags: [] },
  { emoji: '📺', description: 'television', category: 'Objects', aliases: ['tv'], tags: [] },
  { emoji: '📻', description: 'radio', category: 'Objects', aliases: ['radio'], tags: ['podcast'] },
  { emoji: '🎙️', description: 'studio microphone', category: 'Objects', aliases: ['studio_microphone'], tags: ['podcast'] },
  { emoji: '🎚️', description: 'level slider', category: 'Objects', aliases: ['level_slider'], tags: [] },
  { emoji: '🎛️', description: 'control knobs', category: 'Objects', aliases: ['control_knobs'], tags: [] },
  { emoji: '⏱️', description: 'stopwatch', category: 'Objects', aliases: ['stopwatch'], tags: [] },
  { emoji: '⏲️', description: 'timer clock', category: 'Objects', aliases: ['timer_clock'], tags: [] },
  { emoji: '⏰', description: 'alarm clock', category: 'Objects', aliases: ['alarm_clock'], tags: ['morning'] },
  { emoji: '📡', description: 'satellite antenna', category: 'Objects', aliases: ['satellite'], tags: ['signal'] },
  { emoji: '🔋', description: 'battery', category: 'Objects', aliases: ['battery'], tags: ['power'] },
  { emoji: '🔌', description: 'electric plug', category: 'Objects', aliases: ['electric_plug'], tags: [] },
  { emoji: '💡', description: 'light bulb', category: 'Objects', aliases: ['bulb'], tags: ['idea', 'light'] },
  { emoji: '🔦', description: 'flashlight', category: 'Objects', aliases: ['flashlight'], tags: [] },
  { emoji: '🕯️', description: 'candle', category: 'Objects', aliases: ['candle'], tags: [] },
  { emoji: '💸', description: 'money with wings', category: 'Objects', aliases: ['money_with_wings'], tags: ['dollar'] },
  { emoji: '💵', description: 'dollar banknote', category: 'Objects', aliases: ['dollar'], tags: ['money'] },
  { emoji: '💴', description: 'yen banknote', category: 'Objects', aliases: ['yen'], tags: [] },
  { emoji: '💶', description: 'euro banknote', category: 'Objects', aliases: ['euro'], tags: [] },
  { emoji: '💷', description: 'pound banknote', category: 'Objects', aliases: ['pound'], tags: [] },
  { emoji: '💰', description: 'money bag', category: 'Objects', aliases: ['moneybag'], tags: ['dollar', 'rich'] },
  { emoji: '💳', description: 'credit card', category: 'Objects', aliases: ['credit_card'], tags: ['subscription'] },
  { emoji: '💎', description: 'gem stone', category: 'Objects', aliases: ['gem'], tags: ['diamond'] },
  { emoji: '🔧', description: 'wrench', category: 'Objects', aliases: ['wrench'], tags: ['tool'] },
  { emoji: '🔨', description: 'hammer', category: 'Objects', aliases: ['hammer'], tags: ['tool'] },
  { emoji: '⚒️', description: 'hammer and pick', category: 'Objects', aliases: ['hammer_and_pick'], tags: [] },
  { emoji: '🛠️', description: 'hammer and wrench', category: 'Objects', aliases: ['hammer_and_wrench'], tags: [] },
  { emoji: '⛏️', description: 'pick', category: 'Objects', aliases: ['pick'], tags: [] },
  { emoji: '🔩', description: 'nut and bolt', category: 'Objects', aliases: ['nut_and_bolt'], tags: [] },
  { emoji: '⚙️', description: 'gear', category: 'Objects', aliases: ['gear'], tags: [] },
  { emoji: '🔗', description: 'link', category: 'Objects', aliases: ['link'], tags: [] },
  { emoji: '📎', description: 'paperclip', category: 'Objects', aliases: ['paperclip'], tags: [] },
  { emoji: '✂️', description: 'scissors', category: 'Objects', aliases: ['scissors'], tags: ['cut'] },
  { emoji: '📐', description: 'triangular ruler', category: 'Objects', aliases: ['triangular_ruler'], tags: [] },
  { emoji: '📏', description: 'straight ruler', category: 'Objects', aliases: ['straight_ruler'], tags: [] },
  { emoji: '📌', description: 'pushpin', category: 'Objects', aliases: ['pushpin'], tags: ['location'] },
  { emoji: '📍', description: 'round pushpin', category: 'Objects', aliases: ['round_pushpin'], tags: ['location'] },
  { emoji: '🔒', description: 'locked', category: 'Objects', aliases: ['lock'], tags: ['security', 'private'] },
  { emoji: '🔓', description: 'unlocked', category: 'Objects', aliases: ['unlock'], tags: [] },
  { emoji: '🔐', description: 'locked with key', category: 'Objects', aliases: ['closed_lock_with_key'], tags: ['security'] },
  { emoji: '🔑', description: 'key', category: 'Objects', aliases: ['key'], tags: ['lock', 'password'] },
  { emoji: '📝', description: 'memo', category: 'Objects', aliases: ['memo', 'pencil'], tags: ['document', 'note'] },
  { emoji: '✏️', description: 'pencil', category: 'Objects', aliases: ['pencil2'], tags: [] },
  { emoji: '✒️', description: 'black nib', category: 'Objects', aliases: ['black_nib'], tags: [] },
  { emoji: '🖊️', description: 'pen', category: 'Objects', aliases: ['pen'], tags: [] },
  { emoji: '🖋️', description: 'fountain pen', category: 'Objects', aliases: ['fountain_pen'], tags: [] },
  { emoji: '📚', description: 'books', category: 'Objects', aliases: ['books'], tags: ['library'] },
  { emoji: '📖', description: 'open book', category: 'Objects', aliases: ['book', 'open_book'], tags: [] },
  { emoji: '📕', description: 'closed book', category: 'Objects', aliases: ['closed_book'], tags: [] },
  { emoji: '📗', description: 'green book', category: 'Objects', aliases: ['green_book'], tags: [] },
  { emoji: '📘', description: 'blue book', category: 'Objects', aliases: ['blue_book'], tags: [] },
  { emoji: '📙', description: 'orange book', category: 'Objects', aliases: ['orange_book'], tags: [] },
  { emoji: '📓', description: 'notebook', category: 'Objects', aliases: ['notebook'], tags: [] },
  { emoji: '📔', description: 'notebook with decorative cover', category: 'Objects', aliases: ['notebook_with_decorative_cover'], tags: [] },
  { emoji: '📒', description: 'ledger', category: 'Objects', aliases: ['ledger'], tags: [] },
  { emoji: '📃', description: 'page with curl', category: 'Objects', aliases: ['page_with_curl'], tags: [] },
  { emoji: '📄', description: 'page facing up', category: 'Objects', aliases: ['page_facing_up'], tags: ['document'] },
  { emoji: '📰', description: 'newspaper', category: 'Objects', aliases: ['newspaper'], tags: ['press'] },
  { emoji: '📁', description: 'file folder', category: 'Objects', aliases: ['file_folder'], tags: ['directory'] },
  { emoji: '📂', description: 'open file folder', category: 'Objects', aliases: ['open_file_folder'], tags: [] },
  { emoji: '📅', description: 'calendar', category: 'Objects', aliases: ['date'], tags: ['calendar', 'schedule'] },
  { emoji: '📆', description: 'tear-off calendar', category: 'Objects', aliases: ['calendar'], tags: ['schedule'] },
  { emoji: '📊', description: 'bar chart', category: 'Objects', aliases: ['bar_chart'], tags: ['stats', 'metrics'] },
  { emoji: '📈', description: 'chart increasing', category: 'Objects', aliases: ['chart_with_upwards_trend'], tags: ['graph', 'metrics'] },
  { emoji: '📉', description: 'chart decreasing', category: 'Objects', aliases: ['chart_with_downwards_trend'], tags: ['graph', 'metrics'] },
  { emoji: '📋', description: 'clipboard', category: 'Objects', aliases: ['clipboard'], tags: [] },
  { emoji: '✉️', description: 'envelope', category: 'Objects', aliases: ['email', 'envelope'], tags: ['letter'] },
  { emoji: '📧', description: 'e-mail', category: 'Objects', aliases: ['e-mail'], tags: [] },
  { emoji: '📨', description: 'incoming envelope', category: 'Objects', aliases: ['incoming_envelope'], tags: [] },
  { emoji: '📩', description: 'envelope with arrow', category: 'Objects', aliases: ['envelope_with_arrow'], tags: [] },
  { emoji: '📤', description: 'outbox tray', category: 'Objects', aliases: ['outbox_tray'], tags: [] },
  { emoji: '📥', description: 'inbox tray', category: 'Objects', aliases: ['inbox_tray'], tags: [] },
  { emoji: '📦', description: 'package', category: 'Objects', aliases: ['package'], tags: ['shipping'] },
  { emoji: '🏷️', description: 'label', category: 'Objects', aliases: ['label'], tags: ['tag'] },
  { emoji: '🔖', description: 'bookmark', category: 'Objects', aliases: ['bookmark'], tags: [] },

  // Symbols
  { emoji: '❤️', description: 'red heart', category: 'Symbols', aliases: ['heart'], tags: ['love'] },
  { emoji: '✅', description: 'check mark button', category: 'Symbols', aliases: ['white_check_mark'], tags: [] },
  { emoji: '❌', description: 'cross mark', category: 'Symbols', aliases: ['x'], tags: [] },
  { emoji: '❓', description: 'question mark', category: 'Symbols', aliases: ['question'], tags: ['confused'] },
  { emoji: '❗', description: 'exclamation mark', category: 'Symbols', aliases: ['exclamation', 'heavy_exclamation_mark'], tags: ['bang'] },
  { emoji: '⭐', description: 'star', category: 'Symbols', aliases: ['star'], tags: [] },
  { emoji: '🌟', description: 'glowing star', category: 'Symbols', aliases: ['star2'], tags: [] },
  { emoji: '✨', description: 'sparkles', category: 'Symbols', aliases: ['sparkles'], tags: ['shiny'] },
  { emoji: '🔥', description: 'fire', category: 'Symbols', aliases: ['fire'], tags: ['hot', 'lit'] },
  { emoji: '💧', description: 'droplet', category: 'Symbols', aliases: ['droplet'], tags: ['water'] },
  { emoji: '🎵', description: 'musical note', category: 'Symbols', aliases: ['musical_note'], tags: [] },
  { emoji: '🎶', description: 'musical notes', category: 'Symbols', aliases: ['notes'], tags: ['music'] },
  { emoji: '➡️', description: 'right arrow', category: 'Symbols', aliases: ['arrow_right'], tags: [] },
  { emoji: '⬅️', description: 'left arrow', category: 'Symbols', aliases: ['arrow_left'], tags: [] },
  { emoji: '⬆️', description: 'up arrow', category: 'Symbols', aliases: ['arrow_up'], tags: [] },
  { emoji: '⬇️', description: 'down arrow', category: 'Symbols', aliases: ['arrow_down'], tags: [] },
  { emoji: '🔄', description: 'counterclockwise arrows button', category: 'Symbols', aliases: ['arrows_counterclockwise'], tags: ['sync', 'refresh'] },
  { emoji: '➕', description: 'plus', category: 'Symbols', aliases: ['heavy_plus_sign'], tags: [] },
  { emoji: '➖', description: 'minus', category: 'Symbols', aliases: ['heavy_minus_sign'], tags: [] },
  { emoji: '✖️', description: 'multiply', category: 'Symbols', aliases: ['heavy_multiplication_x'], tags: [] },
  { emoji: '➗', description: 'divide', category: 'Symbols', aliases: ['heavy_division_sign'], tags: [] },
  { emoji: '💲', description: 'heavy dollar sign', category: 'Symbols', aliases: ['heavy_dollar_sign'], tags: [] },
  { emoji: '©️', description: 'copyright', category: 'Symbols', aliases: ['copyright'], tags: [] },
  { emoji: '®️', description: 'registered', category: 'Symbols', aliases: ['registered'], tags: [] },
  { emoji: '™️', description: 'trade mark', category: 'Symbols', aliases: ['tm'], tags: ['trademark'] },
  { emoji: '🔴', description: 'red circle', category: 'Symbols', aliases: ['red_circle'], tags: [] },
  { emoji: '🟠', description: 'orange circle', category: 'Symbols', aliases: ['orange_circle'], tags: [] },
  { emoji: '🟡', description: 'yellow circle', category: 'Symbols', aliases: ['yellow_circle'], tags: [] },
  { emoji: '🟢', description: 'green circle', category: 'Symbols', aliases: ['green_circle'], tags: [] },
  { emoji: '🔵', description: 'blue circle', category: 'Symbols', aliases: ['large_blue_circle'], tags: [] },
  { emoji: '🟣', description: 'purple circle', category: 'Symbols', aliases: ['purple_circle'], tags: [] },
  { emoji: '⚫', description: 'black circle', category: 'Symbols', aliases: ['black_circle'], tags: [] },
  { emoji: '⚪', description: 'white circle', category: 'Symbols', aliases: ['white_circle'], tags: [] },
  { emoji: '🟤', description: 'brown circle', category: 'Symbols', aliases: ['brown_circle'], tags: [] },
  { emoji: '🔺', description: 'red triangle pointed up', category: 'Symbols', aliases: ['small_red_triangle'], tags: [] },
  { emoji: '🔻', description: 'red triangle pointed down', category: 'Symbols', aliases: ['small_red_triangle_down'], tags: [] },
  { emoji: '🔶', description: 'large orange diamond', category: 'Symbols', aliases: ['large_orange_diamond'], tags: [] },
  { emoji: '🔷', description: 'large blue diamond', category: 'Symbols', aliases: ['large_blue_diamond'], tags: [] },
  { emoji: '🔸', description: 'small orange diamond', category: 'Symbols', aliases: ['small_orange_diamond'], tags: [] },
  { emoji: '🔹', description: 'small blue diamond', category: 'Symbols', aliases: ['small_blue_diamond'], tags: [] },

  // Flags (common ones)
  { emoji: '🏳️', description: 'white flag', category: 'Flags', aliases: ['white_flag'], tags: [] },
  { emoji: '🏴', description: 'black flag', category: 'Flags', aliases: ['black_flag'], tags: [] },
  { emoji: '🏁', description: 'chequered flag', category: 'Flags', aliases: ['checkered_flag'], tags: ['milestone', 'finish'] },
  { emoji: '🚩', description: 'triangular flag', category: 'Flags', aliases: ['triangular_flag_on_post'], tags: [] },
  { emoji: '🎌', description: 'crossed flags', category: 'Flags', aliases: ['crossed_flags'], tags: [] },
  { emoji: '🏳️‍🌈', description: 'rainbow flag', category: 'Flags', aliases: ['rainbow_flag'], tags: ['pride'] },

  // Misc popular
  { emoji: '🎉', description: 'party popper', category: 'Activities', aliases: ['tada'], tags: ['party', 'congratulations'] },
  { emoji: '🎊', description: 'confetti ball', category: 'Activities', aliases: ['confetti_ball'], tags: [] },
  { emoji: '🎈', description: 'balloon', category: 'Activities', aliases: ['balloon'], tags: ['party', 'birthday'] },
  { emoji: '🎁', description: 'wrapped gift', category: 'Activities', aliases: ['gift'], tags: ['present', 'birthday', 'christmas'] },
  { emoji: '🏆', description: 'trophy', category: 'Activities', aliases: ['trophy'], tags: ['award', 'contest', 'winner'] },
  { emoji: '🥇', description: 'first place medal', category: 'Activities', aliases: ['1st_place_medal'], tags: ['gold'] },
  { emoji: '🥈', description: 'second place medal', category: 'Activities', aliases: ['2nd_place_medal'], tags: ['silver'] },
  { emoji: '🥉', description: 'third place medal', category: 'Activities', aliases: ['3rd_place_medal'], tags: ['bronze'] },
  { emoji: '🎪', description: 'circus tent', category: 'Activities', aliases: ['circus_tent'], tags: [] },
  { emoji: '🎭', description: 'performing arts', category: 'Activities', aliases: ['performing_arts'], tags: ['theater', 'drama'] },
  { emoji: '🎨', description: 'artist palette', category: 'Activities', aliases: ['art'], tags: ['design', 'paint'] },
  { emoji: '🎬', description: 'clapper board', category: 'Activities', aliases: ['clapper'], tags: ['film'] },
  { emoji: '🎤', description: 'microphone', category: 'Activities', aliases: ['microphone'], tags: ['sing'] },
  { emoji: '🎧', description: 'headphone', category: 'Activities', aliases: ['headphones'], tags: ['music', 'earphones'] },
  { emoji: '🎹', description: 'musical keyboard', category: 'Activities', aliases: ['musical_keyboard'], tags: ['piano'] },
  { emoji: '🎷', description: 'saxophone', category: 'Activities', aliases: ['saxophone'], tags: [] },
  { emoji: '🎸', description: 'guitar', category: 'Activities', aliases: ['guitar'], tags: ['rock'] },
  { emoji: '🎺', description: 'trumpet', category: 'Activities', aliases: ['trumpet'], tags: [] },
  { emoji: '🎻', description: 'violin', category: 'Activities', aliases: ['violin'], tags: [] },
  { emoji: '🪘', description: 'drum', category: 'Activities', aliases: ['drum'], tags: [] },

  // Weather
  { emoji: '☀️', description: 'sun', category: 'Travel & Places', aliases: ['sunny'], tags: ['weather'] },
  { emoji: '🌤️', description: 'sun behind small cloud', category: 'Travel & Places', aliases: ['sun_behind_small_cloud'], tags: [] },
  { emoji: '⛅', description: 'sun behind cloud', category: 'Travel & Places', aliases: ['partly_sunny'], tags: ['weather', 'cloud'] },
  { emoji: '🌥️', description: 'sun behind large cloud', category: 'Travel & Places', aliases: ['sun_behind_large_cloud'], tags: [] },
  { emoji: '☁️', description: 'cloud', category: 'Travel & Places', aliases: ['cloud'], tags: [] },
  { emoji: '🌦️', description: 'sun behind rain cloud', category: 'Travel & Places', aliases: ['sun_behind_rain_cloud'], tags: [] },
  { emoji: '🌧️', description: 'cloud with rain', category: 'Travel & Places', aliases: ['cloud_with_rain'], tags: [] },
  { emoji: '⛈️', description: 'cloud with lightning and rain', category: 'Travel & Places', aliases: ['cloud_with_lightning_and_rain'], tags: [] },
  { emoji: '🌩️', description: 'cloud with lightning', category: 'Travel & Places', aliases: ['cloud_with_lightning'], tags: [] },
  { emoji: '🌨️', description: 'cloud with snow', category: 'Travel & Places', aliases: ['cloud_with_snow'], tags: [] },
  { emoji: '❄️', description: 'snowflake', category: 'Travel & Places', aliases: ['snowflake'], tags: ['winter', 'cold', 'weather'] },
  { emoji: '☃️', description: 'snowman', category: 'Travel & Places', aliases: ['snowman_with_snow'], tags: ['winter', 'christmas'] },
  { emoji: '⛄', description: 'snowman without snow', category: 'Travel & Places', aliases: ['snowman'], tags: ['winter'] },
  { emoji: '🌪️', description: 'tornado', category: 'Travel & Places', aliases: ['tornado'], tags: [] },
  { emoji: '🌫️', description: 'fog', category: 'Travel & Places', aliases: ['fog'], tags: [] },
  { emoji: '🌊', description: 'water wave', category: 'Travel & Places', aliases: ['ocean'], tags: ['sea'] },
  { emoji: '🌈', description: 'rainbow', category: 'Travel & Places', aliases: ['rainbow'], tags: [] },
  { emoji: '⚡', description: 'high voltage', category: 'Travel & Places', aliases: ['zap'], tags: ['lightning', 'thunder'] },
  { emoji: '🌙', description: 'crescent moon', category: 'Travel & Places', aliases: ['crescent_moon'], tags: ['night'] },
  { emoji: '🌕', description: 'full moon', category: 'Travel & Places', aliases: ['full_moon'], tags: [] },
  { emoji: '🌑', description: 'new moon', category: 'Travel & Places', aliases: ['new_moon'], tags: [] },
  { emoji: '🌛', description: 'first quarter moon face', category: 'Travel & Places', aliases: ['first_quarter_moon_with_face'], tags: [] },
  { emoji: '🌜', description: 'last quarter moon face', category: 'Travel & Places', aliases: ['last_quarter_moon_with_face'], tags: [] },
  { emoji: '🌝', description: 'full moon face', category: 'Travel & Places', aliases: ['full_moon_with_face'], tags: [] },
  { emoji: '🌞', description: 'sun with face', category: 'Travel & Places', aliases: ['sun_with_face'], tags: ['summer'] },
  { emoji: '⭐', description: 'star', category: 'Travel & Places', aliases: ['star'], tags: [] },
  { emoji: '🌟', description: 'glowing star', category: 'Travel & Places', aliases: ['star2'], tags: [] },
  { emoji: '🌠', description: 'shooting star', category: 'Travel & Places', aliases: ['stars'], tags: [] },
  { emoji: '🪐', description: 'ringed planet', category: 'Travel & Places', aliases: ['ringed_planet'], tags: ['saturn'] },
  { emoji: '🚀', description: 'rocket', category: 'Travel & Places', aliases: ['rocket'], tags: ['ship', 'launch'] },
]

export default emojiList
